version: '3.8'
services:
  db:
    container_name: db
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "defaultuser"
      POSTGRES_PASSWORD: "randompassword"
      POSTGRES_DB: "db_name"
  test-db:
    container_name: test-db
    image: postgres:17
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "testpassword"
      POSTGRES_DB: "test_db"
